export default function capitalizationFilter(word) {
  switch (word.toUpperCase()) {
    case 'AGK':
    case 'BERJ':
    case 'BM':
    case 'BNDES':
    case 'BNP':
    case 'BPP':
    case 'B3':
    case 'BI':
    case 'BBI':
    case 'BMG':
    case 'BMS':
    case 'BBM':
    case 'BV':
    case 'BR':
    case 'BRB':
    case 'BRK':
    case 'BRL':
    case 'BGC':
    case 'B&T':
    case 'BNY':
    case 'CC':
    case 'CCM':
    case 'CDC':
    case 'CM':
    case 'CCR':
    case 'CVM':
    case 'CCVM':
    case 'CCTVM':
    case 'CTVM':
    case 'CECM':
    case 'CIA':
    case 'CVC':
    case 'CCV':
    case 'CFI':
    case 'C.F.I.':
    case 'CSF':
    case 'CV':
    case 'C6':
    case 'DTVM':
    case 'E':
    case 'EFX':
    case 'FFA':
    case 'GB':
    case 'GM':
    case 'IB':
    case 'ID':
    case 'IP':
    case 'I.P.':
    case 'HS':
    case 'HSBC':
    case 'KDB':
    case 'LTDA':
    case 'LTDA.':
    case 'MS':
    case 'N.A.':
    case 'NU':
    case 'OM':
    case 'OZ':
    case 'PA':
    case 'QI':
    case 'RB':
    case 'RDV':
    case 'RJI':
    case 'RNX':
    case 'RS':
    case 'SA':
    case 'S.A':
    case 'S.A.':
    case 'S.A.CFI':
    case 'S/A':
    case 'SCD':
    case 'SCFI':
    case 'SCMEPP':
    case 'SC':
    case 'SE':
    case 'SCM':
    case 'SP':
    case 'UBS':
    case 'UY3':
    case 'VR':
    case 'XP':
      return word;
  }

  if (word.toUpperCase() == 'BCO' || word.toUpperCase() == 'BCO.') {
    return 'Banco';
  }
}